[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@libsql/client"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200